// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ConsoleApp3.Models;

public partial class TestVarchar
{
    public int Id { get; set; }

    public string Tname { get; set; }

    public string Tvalue { get; set; }
}